vich_uploader:
    db_driver: orm

    mappings:
        attachmentFile:
            uri_prefix: '%attachmentFile%'
            upload_destination: '%kernel.project_dir%/public%attachmentFile%'
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d' # will create directory "2021/06/28" for created date
                    date_time_property: createdAt
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
